trending_url = "https://gaana.com/apiv2?country=IN&type=miscTrendingSongs"
search_songs_url = "https://gsearch.gaana.com/vichitih/go/v2?geoLocation=IN&content_filter=2&isRegSrch=0&webVersion=mix&autocomplete=0&rType=web&usrLang=&include=track&query="
song_details_url = "https://gaana.com/apiv2?country=IN&type=songDetail&seokey="
#similar_songs_url = "https://gaana.com/apiv2?type=songSimilar&id=" ## Removed for now as the endpoint seems to return nothing
#similar_albums_url = "https://gaana.com/apiv2?type=albumSimilar&id="
similar_artists_url = "https://apiv2.gaana.com/player/similar-artists/" ## Mobile-specific endpoint
playlist_details_url = "https://gaana.com/apiv2?country=IN&type=playlistDetail&seokey="
search_playlists_url = "https://gsearch.gaana.com/vichitih/go/v2?geoLocation=IN&content_filter=2&isRegSrch=0&webVersion=mix&autocomplete=0&rType=web&usrLang=&include=playlist&query="
new_releases_url = "https://gaana.com/apiv2?country=IN&page=0&type=miscNewRelease&language="
charts_url = "https://apiv2.gaana.com/home/playlist/top-charts?country=IN&view=all&limit=0,"
search_artists_url = "https://gsearch.gaana.com/vichitih/go/v2?geoLocation=IN&content_filter=2&isRegSrch=0&webVersion=mix&autocomplete=0&rType=web&usrLang=&include=artist&query="
artist_details_url = "https://gaana.com/apiv2?country=IN&type=artistDetail&seokey="
artist_top_tracks = "https://gaana.com/apiv2?country=IN&language=&order=0&page=0&sortBy=popularity&type=artistTrackList&id="
search_albums_url = "https://gsearch.gaana.com/vichitih/go/v2?geoLocation=IN&content_filter=2&isRegSrch=0&webVersion=mix&autocomplete=0&rType=web&usrLang=&include=album&query="
album_details_url = "https://gaana.com/apiv2?country=IN&type=albumDetail&seokey="
similar_albums_url = "https://rec.gaana.com/recommendation/similarAlbums/"
artist_tracks_url = "https://apiv2.gaana.com/home/artist/tracks/"
